import test from 'node:test';
import assert from 'node:assert/strict';
import {Battle,HEROES} from '../src/engine.js';

function game(player='su_anasy',enemy='kremlin'){const b=new Battle({player,enemy,ai:false});b.start();for(const e of Object.values(b.entities))e.nextAuto=Infinity;b.drain();return b;}
function advance(b,seconds){for(let elapsed=0;elapsed<seconds-1e-7;elapsed+=1/60)b.step(Math.min(1/60,seconds-elapsed));}

test('auto-attacks require aligned lanes and produce attack and hit events',()=>{const b=game();b.entities.player.nextAuto=0;b.entities.enemy.lane=2;advance(b,1);assert.equal(b.projectiles.length,0);b.entities.enemy.lane=1;advance(b,.1);assert.equal(b.entities.player.pose,'attack');advance(b,.6);assert.equal(b.entities.enemy.hp,136);assert(b.drain().some(e=>e.type==='HIT'));});
test('a lane change dodges an in-flight ordinary projectile',()=>{const b=game();b.entities.enemy.nextAuto=0;advance(b,.1);assert(b.move('player',0));advance(b,.6);assert.equal(b.entities.player.hp,120);});
test('golden comb has warning delay, damage and two-second root',()=>{const b=game();assert(b.cast('player',1));advance(b,.6);assert.equal(b.entities.enemy.hp,144);advance(b,.3);assert.equal(b.entities.enemy.hp,126);assert(b.entities.enemy.rootUntil>b.time);assert.equal(b.move('enemy',0),false);assert(b.cast('enemy',0),'root must not silence skills');});
test('Su anasy wave removes root and reflects incoming ordinary projectile',()=>{const b=game();b.entities.player.rootUntil=10;b.entities.enemy.nextAuto=0;advance(b,.1);assert(b.cast('player',0));assert.equal(b.entities.player.rootUntil,0);advance(b,1);assert.equal(b.entities.player.hp,120);assert.equal(b.stats.reflections,1);assert.equal(b.entities.enemy.hp,121);});
test('reflection expires after 1.6 seconds',()=>{const b=game();b.cast('player',0);advance(b,1.7);b.resolve({kind:'auto',target:'player',source:'enemy',lane:1,damage:9});assert.equal(b.entities.player.hp,111);});
test('reflected projectiles can be dodged and do not loop infinitely',()=>{const b=game('su_anasy','su_anasy');b.entities.player.reflectUntil=9;b.entities.enemy.reflectUntil=9;b.resolve({kind:'auto',source:'enemy',target:'player',lane:1,damage:8});advance(b,.6);assert.equal(b.entities.enemy.hp,112);assert.equal(b.projectiles.length,0);});
test('ground seal traps a target standing in the lane until the gate expires',()=>{const b=game();b.cast('enemy',1);advance(b,.2);b.cast('player',0);advance(b,1.5);assert.equal(b.entities.player.hp,96);assert(b.closed.player[1]>b.time);assert.equal(b.entities.player.gateTrapUntil,b.closed.player[1]);assert.equal(b.move('player',0),false);assert(b.cast('player',1),'gates do not silence skills');advance(b,4);assert(b.move('player',0));});
test('cleansing a root does not open a gate that trapped the player',()=>{const b=game();b.cast('enemy',1);advance(b,1.7);b.entities.player.rootUntil=b.time+2;assert(b.cast('player',0));assert.equal(b.entities.player.rootUntil,0);assert.equal(b.move('player',0),false);advance(b,4);assert(b.move('player',0));});
test('seal closes its marked lane even if target dodges',()=>{const b=game();b.cast('enemy',1);assert(b.move('player',0));advance(b,1.7);assert.equal(b.entities.player.hp,120);assert(b.closed.player[1]>b.time);});
test('wall has 32 shield, roots for 2 seconds and allows other ability',()=>{const b=game('kremlin','su_anasy');assert(b.cast('player',0));assert.equal(b.entities.player.shield,32);assert.equal(b.move('player',2),false);assert(b.cast('player',1));b.hurt('player',40,'enemy');assert.equal(b.entities.player.hp,136);assert.equal(b.entities.player.shield,0);advance(b,2.1);assert(b.move('player',2));});
test('unused shield expires after 4 seconds',()=>{const b=game('kremlin','su_anasy');b.cast('player',0);advance(b,4.1);assert.equal(b.entities.player.shield,0);});
test('pause freezes clock, warnings and cooldowns, blocks inputs',()=>{const b=game();b.cast('enemy',1);advance(b,.3);const t=b.time,due=b.pending[0].due;b.pause();advance(b,4);assert.equal(b.time,t);assert.equal(b.pending[0].due,due);assert.equal(b.move('player',0),false);assert.equal(b.cast('player',0),false);b.resume();advance(b,1.4);assert.equal(b.entities.player.hp,96);});
test('abilities cannot be replayed during cooldown',()=>{const b=game();assert(b.cast('player',1));assert.equal(b.cast('player',1),false);advance(b,7.1);assert(b.cast('player',1));});
test('finish emits once, uses defeat sprite and rejects further actions',()=>{const b=game();b.hurt('enemy',999,'player');b.step(.01);assert.equal(b.status,'finished');assert.equal(b.result,'win');assert.equal(b.entities.enemy.pose,'defeat');assert.equal(b.cast('player',1),false);advance(b,10);assert.equal(b.drain().filter(e=>e.type==='FINISH').length,1);});
test('90-second result compares health proportions and supports a draw',()=>{const b=game();b.entities.player.hp=60;b.entities.enemy.hp=60;advance(b,91);assert.equal(b.time,90);assert.equal(b.result,'win');const tied=game();advance(tied,90.1);assert.equal(tied.result,'draw');});
test('invalid inputs do not alter game state',()=>{const b=game();assert.equal(b.move('player',-1),false);assert.equal(b.move('player',1.3),false);assert.equal(b.cast('player',7),false);b.step(NaN);assert.equal(b.time,0);});
test('tickle waits 1.4 seconds, roots without damage, allows skills',()=>{const b=game('shurale','su_anasy');b.cast('player',0);advance(b,1.3);assert.equal(b.entities.enemy.rootUntil,0);advance(b,.2);assert.equal(b.entities.enemy.hp,120);assert(b.entities.enemy.rootUntil>b.time);assert.equal(b.move('enemy',0),false);assert(b.cast('enemy',0));assert.equal(b.entities.enemy.rootUntil,0);});
test('tickle fixes its lane at cast time and can be dodged',()=>{const b=game('shurale','kremlin');b.cast('player',0);b.move('enemy',0);advance(b,1.5);assert.equal(b.entities.enemy.rootUntil,0);assert.equal(b.entities.enemy.hp,144);});
test('mist blocks ordinary shots, including reflected shots, but not skills',()=>{const b=game('shurale','su_anasy');b.cast('player',1);b.resolve({kind:'auto',target:'player',source:'enemy',lane:1,damage:8});b.resolve({kind:'auto',target:'player',source:'enemy',lane:1,damage:8,reflected:true});assert.equal(b.entities.player.hp,124);b.resolve({kind:'comb',target:'player',source:'enemy',lane:1,damage:18,root:2});assert.equal(b.entities.player.hp,106);assert(b.entities.player.rootUntil>b.time);b.resolve({kind:'wave',target:'player',source:'enemy',lane:1,damage:14,ground:true});assert.equal(b.entities.player.hp,92);advance(b,3.1);b.resolve({kind:'auto',target:'player',source:'enemy',lane:1,damage:8});assert.equal(b.entities.player.hp,84);});
test('will cleanses tickle and absorbs exactly 22 damage, no self-root',()=>{const b=game('syuyumbike','shurale');b.cast('enemy',0);advance(b,1.5);assert(b.entities.player.rootUntil>b.time);assert(b.cast('player',0));assert.equal(b.entities.player.rootUntil,0);assert.equal(b.entities.player.shield,22);assert(b.move('player',0));b.hurt('player',30,'enemy');assert.equal(b.entities.player.hp,120);assert.equal(b.entities.player.shield,0);});
test('will shield expires at four seconds',()=>{const b=game('syuyumbike','shurale');b.cast('player',0);advance(b,4.1);assert.equal(b.entities.player.shield,0);});
test('voice telegraphs exactly two lanes, deals damage only once after 1.5 s',()=>{const b=game('syuyumbike','kremlin');b.cast('player',1);assert.deepEqual(b.pending[0].lanes,[1,2]);b.move('enemy',2);advance(b,1.4);assert.equal(b.entities.enemy.hp,144);advance(b,.2);assert.equal(b.entities.enemy.hp,124);assert(b.entities.enemy.weakenUntil>b.time);assert.equal(b.drain().filter(e=>e.type==='HIT').length,1);});
test('safe voice lane avoids both damage and weakening',()=>{const b=game('syuyumbike','shurale');b.cast('player',1);b.move('enemy',0);advance(b,1.6);assert.equal(b.entities.enemy.hp,124);assert.equal(b.entities.enemy.weakenUntil,0);});
test('voice halves new auto projectiles for 4s but leaves ability damage intact',()=>{const b=game('syuyumbike','kremlin');b.cast('player',1);advance(b,1.6);b.entities.enemy.nextAuto=b.time;b.step(.01);assert.equal(b.projectiles[0].damage,4.5);b.cast('enemy',1);assert.equal(b.pending[0].damage,24);advance(b,4.1);b.entities.enemy.nextAuto=b.time;b.step(.01);assert.equal(b.projectiles.at(-1).damage,9);});
test('voice passes mist and reflection; root and weaken pause with game time',()=>{const b=game('syuyumbike','shurale');b.cast('enemy',1);b.entities.enemy.reflectUntil=10;b.cast('player',1);advance(b,1.6);assert.equal(b.entities.enemy.hp,104);const until=b.entities.enemy.weakenUntil;b.pause();advance(b,10);assert.equal(b.entities.enemy.weakenUntil,until);assert(b.entities.enemy.weakenUntil>b.time);});
test('all sixteen hero matchups finish safely and both new bots use both skills',()=>{for(const player of Object.keys(HEROES))for(const enemy of Object.keys(HEROES)){let seed=997;const random=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};const b=new Battle({player,enemy,random});b.start();for(let n=0;n<5600&&b.status==='playing';n++){if(n%60===0)b.cast('player',n%120===0?0:1);if(n%91===0)b.move('player',Math.floor(random()*3));b.step(1/60);}assert.equal(b.status,'finished',`${player} vs ${enemy}`);for(const e of Object.values(b.entities)){assert(e.hp>=0);assert(e.hp<=e.maxHp);}if(['shurale','syuyumbike'].includes(enemy))for(const slot of [0,1])assert(b.events.some(e=>e.type==='CAST'&&e.id==='enemy'&&e.slot===slot),`${enemy} skill ${slot}`);}});
test('seeded PvE simulation terminates safely with both hero assignments',()=>{for(const player of ['su_anasy','kremlin']){let seed=137;const random=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};const b=new Battle({player,enemy:player==='su_anasy'?'kremlin':'su_anasy',random});b.start();for(let n=0;n<6000&&b.status==='playing';n++){if(n%80===0)b.cast('player',n%160===0?0:1);if(n%90===0)b.move('player',Math.floor(random()*3));b.step(1/60);}assert.equal(b.status,'finished');assert(b.time<=90);for(const e of Object.values(b.entities)){assert(e.hp>=0);assert(e.hp<=e.maxHp);}assert(b.events.some(e=>e.type==='CAST'));}});
