create table if not exists public.ar_targets (
  id bigint generated by default as identity primary key,
  tag text not null unique,
  entity_id text not null check (entity_id in ('shurale', 'syuyumbike', 'su-anasy', 'kereml')),
  mind_path text not null,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.ar_targets enable row level security;

drop policy if exists "Players can read active AR targets" on public.ar_targets;
create policy "Players can read active AR targets"
  on public.ar_targets for select
  to authenticated
  using (active);

grant select on public.ar_targets to authenticated;

insert into public.ar_targets (
  tag,
  entity_id,
  mind_path,
  latitude,
  longitude,
  active
)
values (
  'stone-01',
  'kereml',
  '/ar/assets/target.mind',
  55.79194444444444,
  49.102222222222224,
  true
)
on conflict (tag) do update set
  entity_id = excluded.entity_id,
  mind_path = excluded.mind_path,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  active = excluded.active;
