// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Miras.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Miras.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Miras.Api.Models.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnemyAttack")
                        .HasColumnType("integer");

                    b.Property<int>("EnemyCurrentHp")
                        .HasColumnType("integer");

                    b.Property<int>("EnemyDefense")
                        .HasColumnType("integer");

                    b.Property<int>("EnemyEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("EnemyMaxHp")
                        .HasColumnType("integer");

                    b.Property<bool>("PlayerAbilityUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerAttack")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerCurrentHp")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerDefense")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerMaxHp")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Reward")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Turn")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnemyEntityId");

                    b.HasIndex("PlayerEntityId");

                    b.HasIndex("UserId");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("Miras.Api.Models.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("Miras.Api.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AbilityDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AbilityPower")
                        .HasColumnType("integer");

                    b.Property<int>("BaseAttack")
                        .HasColumnType("integer");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("integer");

                    b.Property<int>("BaseHp")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbilityDescription = "Шурале призывает корни деревьев, нанося мощный удар и замедляя врага.",
                            AbilityName = "Корни леса",
                            AbilityPower = 35,
                            BaseAttack = 18,
                            BaseDefense = 12,
                            BaseHp = 100,
                            Category = "Дух леса",
                            Description = "Лесной дух из татарских сказок, озорной и хитрый. Любит щекотать заблудившихся путников.",
                            Name = "Шурале",
                            Slug = "shurale",
                            Story = "В дремучем лесу, где вековые дубы переплетают свои кроны, обитает Шурале — лесной дух с длинными пальцами и рогом на лбу. Он известен тем, что заманивает путников в чащу и щекочет их до изнеможения. Но однажды храбрый дровосек по имени Былтыр перехитрил Шурале, зажав его пальцы в расщелине бревна. С тех пор Шурале стал осторожнее, но не утратил своего озорного нрава. Эту историю рассказал великий татарский поэт Габдулла Тукай в своей знаменитой поэме."
                        },
                        new
                        {
                            Id = 2,
                            AbilityDescription = "Су анасы обрушивает волну лунной воды, исцеляя себя и нанося урон врагу.",
                            AbilityName = "Лунный прилив",
                            AbilityPower = 30,
                            BaseAttack = 20,
                            BaseDefense = 10,
                            BaseHp = 95,
                            Category = "Водный дух",
                            Description = "Водяная, хозяйка рек и озёр. Расчёсывает золотые волосы на берегу под лунным светом.",
                            Name = "Су анасы",
                            Slug = "su-anasy",
                            Story = "На берегах озера Кабан в лунные ночи можно увидеть Су анасы — водяную деву с длинными золотыми волосами. Она сидит на камне и расчёсывает их золотым гребнем. Говорят, если кто-то сумеет завладеть её гребнем, она исполнит любое желание. Но горе тому, кто разгневает хозяйку вод — она утащит его на дно. Старики рассказывают, что Су анасы охраняет сокровища ханов, спрятанные на дне Кабана при падении Казани."
                        },
                        new
                        {
                            Id = 3,
                            AbilityDescription = "Башня озаряется светом прошлого, повышая защиту и ослабляя атаку врага.",
                            AbilityName = "Свет памяти",
                            AbilityPower = 25,
                            BaseAttack = 15,
                            BaseDefense = 16,
                            BaseHp = 110,
                            Category = "Историческая святыня",
                            Description = "Падающая башня Казанского Кремля, символ мудрости и верности царицы Сююмбике.",
                            Name = "Башня Сююмбике",
                            Slug = "syuyumbike",
                            Story = "Башня Сююмбике — одна из падающих башен мира, стоящая в сердце Казанского Кремля. По легенде, царица Сююмбике, последняя правительница Казанского ханства, бросилась с её вершины, не желая подчиниться Ивану Грозному. Она попросила построить башню в семь ярусов за семь дней, и каждый день возводился новый ярус. Когда башня была готова, Сююмбике поднялась на самый верх и шагнула в вечность, став символом свободы и верности своему народу."
                        },
                        new
                        {
                            Id = 4,
                            AbilityDescription = "Кремль обрушивает каменные стены на врага, нанося огромный урон.",
                            AbilityName = "Каменная печать",
                            AbilityPower = 40,
                            BaseAttack = 14,
                            BaseDefense = 18,
                            BaseHp = 120,
                            Category = "Крепость-памятник",
                            Description = "Белокаменная крепость, объект ЮНЕСКО. Вечный страж на слиянии Волги и Казанки.",
                            Name = "Казанский Кремль",
                            Slug = "kereml",
                            Story = "Казанский Кремль — древняя цитадель, стоящая на холме у слияния рек Волги и Казанки уже более тысячи лет. Он помнит булгарских князей, ханов Золотой Орды и казанских правителей. По легенде, крепость была основана на месте, где колдун-змей Зилант свил своё гнездо. Жители изгнали змея, и он поселился на озере Кабан, а в память о победе Зилант стал символом города. Стены Кремля хранят дух тысячелетий и силу всех народов, живших под его защитой."
                        });
                });

            modelBuilder.Entity("Miras.Api.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NfcToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("NfcToken")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntityId = 1,
                            Name = "Лесопарк Лебяжье",
                            NfcToken = "SHURALE_NFC"
                        },
                        new
                        {
                            Id = 2,
                            EntityId = 2,
                            Name = "Озеро Кабан",
                            NfcToken = "SUANASY_NFC"
                        },
                        new
                        {
                            Id = 3,
                            EntityId = 3,
                            Name = "Башня Сююмбике",
                            NfcToken = "SYUYUMBIKE_NFC"
                        },
                        new
                        {
                            Id = 4,
                            EntityId = 4,
                            Name = "Казанский Кремль",
                            NfcToken = "ABC123"
                        });
                });

            modelBuilder.Entity("Miras.Api.Models.PveBattle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("integer");

                    b.Property<bool>("RewardApplied")
                        .HasColumnType("boolean");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("PveBattles");
                });

            modelBuilder.Entity("Miras.Api.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectOption = "B",
                            EntityId = 1,
                            OptionA = "Батыр",
                            OptionB = "Былтыр",
                            OptionC = "Алтынчеч",
                            OptionD = "Камыр",
                            Text = "Как зовут дровосека, который перехитрил Шурале в поэме Тукая?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectOption = "C",
                            EntityId = 1,
                            OptionA = "Пугает криками",
                            OptionB = "Запутывает дороги",
                            OptionC = "Щекочет до изнеможения",
                            OptionD = "Прячет вещи",
                            Text = "Чем Шурале любит мучить заблудившихся путников?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectOption = "B",
                            EntityId = 1,
                            OptionA = "Крылья за спиной",
                            OptionB = "Рог на лбу",
                            OptionC = "Хвост с кисточкой",
                            OptionD = "Три глаза",
                            Text = "Какой отличительный признак внешности Шурале?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectOption = "C",
                            EntityId = 2,
                            OptionA = "Серебряной расчёской",
                            OptionB = "Деревянным гребнем",
                            OptionC = "Золотым гребнем",
                            OptionD = "Костяным гребнем",
                            Text = "Чем Су анасы расчёсывает свои волосы на берегу?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectOption = "A",
                            EntityId = 2,
                            OptionA = "Озеро Кабан",
                            OptionB = "Озеро Лебяжье",
                            OptionC = "Озеро Раифское",
                            OptionD = "Голубые озёра",
                            Text = "На берегу какого озера по легенде обитает Су анасы?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectOption = "C",
                            EntityId = 2,
                            OptionA = "Древние книги",
                            OptionB = "Волшебный источник",
                            OptionC = "Сокровища ханов",
                            OptionD = "Подводный дворец",
                            Text = "Что, по легенде, охраняет Су анасы на дне озера?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectOption = "C",
                            EntityId = 3,
                            OptionA = "Пять",
                            OptionB = "Шесть",
                            OptionC = "Семь",
                            OptionD = "Восемь",
                            Text = "Сколько ярусов у Башни Сююмбике по легенде?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectOption = "B",
                            EntityId = 3,
                            OptionA = "Дочерью купца",
                            OptionB = "Последней правительницей Казанского ханства",
                            OptionC = "Женой Тукая",
                            OptionD = "Легендарной воительницей",
                            Text = "Кем была Сююмбике?"
                        },
                        new
                        {
                            Id = 9,
                            CorrectOption = "C",
                            EntityId = 3,
                            OptionA = "Самая высокая в России",
                            OptionB = "Построена без единого гвоздя",
                            OptionC = "Является падающей башней",
                            OptionD = "Полностью из мрамора",
                            Text = "Чем знаменита Башня Сююмбике среди архитектурных памятников мира?"
                        },
                        new
                        {
                            Id = 10,
                            CorrectOption = "B",
                            EntityId = 4,
                            OptionA = "Волга и Кама",
                            OptionB = "Волга и Казанка",
                            OptionC = "Кама и Свияга",
                            OptionD = "Казанка и Булак",
                            Text = "У слияния каких рек стоит Казанский Кремль?"
                        },
                        new
                        {
                            Id = 11,
                            CorrectOption = "C",
                            EntityId = 4,
                            OptionA = "Единорог",
                            OptionB = "Грифон",
                            OptionC = "Зилант",
                            OptionD = "Феникс",
                            Text = "Какое мифическое существо стало символом Казани?"
                        },
                        new
                        {
                            Id = 12,
                            CorrectOption = "B",
                            EntityId = 4,
                            OptionA = "Памятник регионального значения",
                            OptionB = "Объект ЮНЕСКО",
                            OptionC = "Музей-заповедник",
                            OptionD = "Национальный парк",
                            Text = "Какой статус имеет Казанский Кремль?"
                        });
                });

            modelBuilder.Entity("Miras.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChakChak")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GameTokenHash")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChakChak = 100,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "batyr"
                        });
                });

            modelBuilder.Entity("Miras.Api.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ObtainedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("UserId", "EntityId")
                        .IsUnique();

                    b.ToTable("UserEntities");
                });

            modelBuilder.Entity("Miras.Api.Models.Battle", b =>
                {
                    b.HasOne("Miras.Api.Models.Entity", "EnemyEntity")
                        .WithMany()
                        .HasForeignKey("EnemyEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miras.Api.Models.UserEntity", "PlayerEntity")
                        .WithMany()
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miras.Api.Models.User", "User")
                        .WithMany("Battles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyEntity");

                    b.Navigation("PlayerEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Miras.Api.Models.Encounter", b =>
                {
                    b.HasOne("Miras.Api.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miras.Api.Models.Location", "Location")
                        .WithMany("Encounters")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miras.Api.Models.User", "User")
                        .WithMany("Encounters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Miras.Api.Models.Location", b =>
                {
                    b.HasOne("Miras.Api.Models.Entity", "Entity")
                        .WithMany("Locations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Miras.Api.Models.PveBattle", b =>
                {
                    b.HasOne("Miras.Api.Models.Encounter", "Encounter")
                        .WithMany()
                        .HasForeignKey("EncounterId");

                    b.HasOne("Miras.Api.Models.User", "User")
                        .WithMany("PveBattles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Miras.Api.Models.Question", b =>
                {
                    b.HasOne("Miras.Api.Models.Entity", "Entity")
                        .WithMany("Questions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Miras.Api.Models.UserEntity", b =>
                {
                    b.HasOne("Miras.Api.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miras.Api.Models.User", "User")
                        .WithMany("UserEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Miras.Api.Models.Entity", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Miras.Api.Models.Location", b =>
                {
                    b.Navigation("Encounters");
                });

            modelBuilder.Entity("Miras.Api.Models.User", b =>
                {
                    b.Navigation("Battles");

                    b.Navigation("Encounters");

                    b.Navigation("PveBattles");

                    b.Navigation("UserEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
